[{


    "emp_code ":214,
    "emp_name ": "Satyananda A.                            ",
    "join_date ": "2002-02-21T18:30:00.000Z ",
    "left_date ": "2002-06-29T18:30:00.000Z ",
    "login ": "satyanand                 ",
    "designation ": "SE     ",
    "employment ": "   ",
    "grade ":0,
    "func ":null,
    "reportsto ":null,
    "priorexp ":null,
    "cardnum ":null,
    "prob_date ":null,
    "conf_date ":null,
    "salary_due ":null,
    "gat_score ":null,
    "testname ":null,
    "test_score ":null,
    "overall_score ":null,
    "bu_code ":null,
    "transfer_date ":null,
    "domain ": "imsspl ",
    "emp_code_entered ": "32004                "}

    ,{ "emp_code ":173, "emp_name ": "Satyanand A                              ",
    "join_date ": "2002-06-30T18:30:00.000Z ",
    "left_date ":null,
    "login ": "satyanand                 ",
    "designation ": "       ",
    "employment ": "EP ",
    "grade ":60,
    "func ":12,
    "reportsto ":514,
    "priorexp ":11,
    "cardnum ": "0809 ",
    "prob_date ": "2002-12-31T18:30:00.000Z ",
    "conf_date ": "2003-06-30T18:30:00.000Z ",
    "salary_due ":null,
    "gat_score ":0,
    "testname ": " ",
    "test_score ":0,
    "overall_score ":0,
    "bu_code ": "BU01       ",
    "transfer_date ": "2007-06-17T18:30:00.000Z ",
    "domain ": "imsspl ",
    "emp_code_entered ": "10757                "}]